//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP_FYP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Medications
    {
        public int m_id { get; set; }
        public string m_name { get; set; }
        public string m_company { get; set; }
    }
}
