//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP_FYP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Users
    {
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_gender { get; set; }
        public string u_dob { get; set; }
        public string u_country { get; set; }
        public string u_province { get; set; }
        public string u_city { get; set; }
        public string u_password { get; set; }
        public string u_waterfac { get; set; }
        public string u_area { get; set; }
        public string u_home { get; set; }
        public string u_food { get; set; }
        public string u_ventilation { get; set; }
        public string u_cnic { get; set; }
    }
}
