//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP_FYP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Vaccinations
    {
        public int uv_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> v_id { get; set; }
        public string uv_dosage { get; set; }
        public string uv_injecteddate { get; set; }
        public string lastUpdated { get; set; }
    }
}
