//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP_FYP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Social_History
    {
        public int sh_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> d_id { get; set; }
        public string s_level { get; set; }
        public string s_relation { get; set; }
        public string lastUpdated { get; set; }
    }
}
