//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP_FYP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Allergies
    {
        public int ua_id { get; set; }
        public int u_id { get; set; }
        public int a_id { get; set; }
        public string ua_Level { get; set; }
        public string ua_StartDate { get; set; }
        public string lastUpdated { get; set; }
    }
}
